version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - dbdata:/var/lib/mysql
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=docker_laravel
      - DB_USERNAME=docker
      - DB_PASSWORD=docker

  db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=docker_laravel
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  dbdata:
